// @ts-nocheck
// This file is autogenerated by the hyperschema compiler
// Schema Version: 4
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 4

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @holebooks/book
const encoding0 = {
  preencode(state, m) {
    const flags =
      (m.pagesRead ? 1 : 0) |
      (m.totalPages ? 2 : 0) |
      (m.dateRead ? 4 : 0) |
      (m.genre ? 8 : 0) |
      (m.rating ? 16 : 0) |
      (m.notes ? 32 : 0) |
      ((version >= 2 && m.isbn) ? 64 : 0) |
      ((version >= 2 && m.coverUrl) ? 128 : 0) |
      ((version >= 3 && m.dateStarted) ? 256 : 0)

    c.string.preencode(state, m.id)
    c.string.preencode(state, m.title)
    c.string.preencode(state, m.author)
    c.string.preencode(state, m.status)
    c.uint.preencode(state, m.progress)
    c.uint.preencode(state, flags)

    if (m.pagesRead) c.uint.preencode(state, m.pagesRead)
    if (m.totalPages) c.uint.preencode(state, m.totalPages)
    c.string.preencode(state, m.dateAdded)
    if (m.dateRead) c.string.preencode(state, m.dateRead)
    if (m.genre) c.string.preencode(state, m.genre)
    if (m.rating) c.uint.preencode(state, m.rating)
    if (m.notes) c.string.preencode(state, m.notes)
    if (version >= 2 && m.isbn) c.string.preencode(state, m.isbn)
    if (version >= 2 && m.coverUrl) c.string.preencode(state, m.coverUrl)
    if (version >= 3 && m.dateStarted) c.string.preencode(state, m.dateStarted)
  },
  encode(state, m) {
    const flags =
      (m.pagesRead ? 1 : 0) |
      (m.totalPages ? 2 : 0) |
      (m.dateRead ? 4 : 0) |
      (m.genre ? 8 : 0) |
      (m.rating ? 16 : 0) |
      (m.notes ? 32 : 0) |
      ((version >= 2 && m.isbn) ? 64 : 0) |
      ((version >= 2 && m.coverUrl) ? 128 : 0) |
      ((version >= 3 && m.dateStarted) ? 256 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.title)
    c.string.encode(state, m.author)
    c.string.encode(state, m.status)
    c.uint.encode(state, m.progress)
    c.uint.encode(state, flags)

    if (m.pagesRead) c.uint.encode(state, m.pagesRead)
    if (m.totalPages) c.uint.encode(state, m.totalPages)
    c.string.encode(state, m.dateAdded)
    if (m.dateRead) c.string.encode(state, m.dateRead)
    if (m.genre) c.string.encode(state, m.genre)
    if (m.rating) c.uint.encode(state, m.rating)
    if (m.notes) c.string.encode(state, m.notes)
    if (version >= 2 && m.isbn) c.string.encode(state, m.isbn)
    if (version >= 2 && m.coverUrl) c.string.encode(state, m.coverUrl)
    if (version >= 3 && m.dateStarted) c.string.encode(state, m.dateStarted)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      title: r1,
      author: r2,
      status: r3,
      progress: r4,
      pagesRead: (flags & 1) !== 0 ? c.uint.decode(state) : 0,
      totalPages: (flags & 2) !== 0 ? c.uint.decode(state) : 0,
      dateAdded: c.string.decode(state),
      dateRead: (flags & 4) !== 0 ? c.string.decode(state) : null,
      genre: (flags & 8) !== 0 ? c.string.decode(state) : null,
      rating: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      notes: (flags & 32) !== 0 ? c.string.decode(state) : null,
      isbn: (version >= 2 && (flags & 64) !== 0) ? c.string.decode(state) : null,
      coverUrl: (version >= 2 && (flags & 128) !== 0) ? c.string.decode(state) : null,
      dateStarted: (version >= 3 && (flags & 256) !== 0) ? c.string.decode(state) : null
    }
  }
}

// @holebooks/cover
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.buffer.preencode(state, m.data)
    c.string.preencode(state, m.contentType)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.buffer.encode(state, m.data)
    c.string.encode(state, m.contentType)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.string.decode(state)

    return {
      id: r0,
      data: r1,
      contentType: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@holebooks/book':
      return encoding0
    case '@holebooks/cover':
      return encoding1
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
